### ISSUE TITLE
Possible inconsistency in spmv_coo_cpu

### ISSUE THREAD

**Issue by frafad** [gwdidonato/hpgda-spring22#5]
Hi, is it possible that here at line 39 `x` and `y` should be swapped when the `read_tuples_transposed` flag is set to `true`? According me and @feDann they should be swapped because when the flag is set to true, `x` holds the column ids and `y` holds the row ids.
https://github.com/gwdidonato/hpgda-spring22/blob/2416e55ce0c6406bf3bab7a8a8f383628fc6bc42/cuda_CONTEST/src/benchmarks/personalized_pagerank.cuh#L37-L41
https://github.com/gwdidonato/hpgda-spring22/blob/2416e55ce0c6406bf3bab7a8a8f383628fc6bc42/cuda_CONTEST/src/benchmarks/personalized_pagerank.cu#L51-L58

**Comment by gwdidonato** [comment]
Nope, because in the matrix formulation you need the X matrix that is T_transposed, where T=(D^-1)A.
In our implementation, we directly load the adjacency matrix A as transposed (both the read_tuples_transposed and sort_tuples flags are true), and we assume the matrix is transposed in the whole implementation.

**Comment by frafad** [comment]
Ok perfect, thanks
